name: publish
on:
  push:
    branches:
      - main
      - 'releases/**'
  schedule:
    - cron: '0 0 * * 0' # Once a week

jobs:
  publish:
    runs-on: ubuntu-24.04-arm
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@master
      #   with:
      #     platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      # The fact that I can't just ${{ var|lowercase }} astounds me
      - name: Change case of image identifier
        id: case
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository_owner }}/${{ github.event.repository.name }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ steps.case.outputs.lowercase }}:latest
